# Commands from reader to turret
FIRE = 'FIRE'
STOP_FIRE = 'STOP_FIRE'
RELEASE_TILT = 'RELEASE_TILT'
TILT_UP = 'TILT_UP'
TILT_DOWN = 'TILT_DOWN'
RELEASE_ROTATE = 'RELEASE_ROTATE'
ROTATE_RIGHT = 'ROTATE_RIGHT'
ROTATE_LEFT = 'ROTATE_LEFT'

# Constants to map ecodes to actual buttons
JOYSTICK = 'BTN_JOYSTICK'
TRIGGER = 'BTN_TRIGGER'
BTN2 = 'BTN_THUMB'
BTN3 = 'BTN_THUMB2'
BTN4 = 'BTN_TOP'
BTN5 = 'BTN_TOP2'
BTN6 = 'BTNPINKIE'
BTN7 = 'BTN_BASE'
